Iter13
pisarevaa/metrics pull request #13
Opened 2024-05-11 08:18 UTC by pisarevaa

2024-05-11 15:31 UTC, gonozov0 requested changes
Хорошая работа была проделана 💪
Оставил пару комментов по улучшению кода
Также вижу явный пробел с пониманием DI и что на самом деле нужно было сделать при реализации DBStorage, запишись на ближайший 1:1, покажу на примерах

2024-05-11 15:31 UTC, gonozov0 commented on internal/agent/agent.go
> +// }
Удаляй сразу ненужный код вместо комментирования,

2024-05-11 15:31 UTC, gonozov0 commented on internal/agent/agent.go
>  			return fmt.Errorf("not supported type: %v", value.Kind())
Это прям очень сильный антипатерн, видимо прошлую итерацию не я ревьюил (может конечно просто не заметил, сорри)
Использование рефлексии сильно усложняет код, и также сильно роняет производительность

Я еще не встречал на своем опыте кейса, где бы рефлексия была оправдана. В твоем кейсе я бы просто инициализовал массив gaugeMetrics сразу нужными значениями из memStats без использования цикла

2024-05-11 15:31 UTC, gonozov0 commented on internal/agent/agent.go
>  			return fmt.Errorf("not supported type: %v", value.Kind())
Можешь не исправлять раз приняли, но я бы рекомендовал исправить

2024-05-11 15:31 UTC, gonozov0 commented on internal/agent/agent.go
> +	for retries > 0 {
отлично, что ты решил сам реализовать логику ретраев, но реализуй тогда свою полноценную гибкую обертку для этого, принимающую функцию
В текущем виде это усложняет читабельность кода бизнес логики

2024-05-11 15:31 UTC, gonozov0 commented on internal/agent/agent.go
> +// }
аналогично

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/config.go
> +	// )
.

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/database.go
> +type MetricsModel interface {
Не совсем понимаю, почему это названо модель метрик
Модель здесь точно неподходящая часть названия и вводит в заблуждение
На мой взгляд логичное название DBStorage

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/database.go
У тебя сейчас в пакете server все собрано в кучу
Давай отделим хотя бы все Storages, сделаем пакет storages внутри server и поместим MemStorage и DBStorage

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/database.go
> +}
По курсу вроде как не требуется, но я рекомендую сразу разобраться с механизмом миграций в go.

Для этого есть 2 популярные библиотеки:
- [golang-migrate/migrate](https://github.com/golang-migrate/migrate)
- [goose](https://github.com/pressly/goose)

Общий механизм одинаков:
1. создаешь отдельно папку в проекте с миграциями
2. описываешь на sql миграцию для создания таблиц, а также отдельную миграцию для ее откатывания (удаления созданных таблиц)
3. в логике инициализации Storage вызываешь применение всех твоих описанных миграций (это не особо правильный подход, в проде все миграции накатываются отдельно перед релизом, но т.к. мы подстраиваемся под прохождение автотестов, то в данном случае оправдано)

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/database.go
> +func (dbpool *DBPool) InsertRowsIntoDBWithRetry(ctx context.Context, metrics []Metrics) error {
Это очень опасно что-то вставлять в базу с ретраями. У тебя может на самом деле успешно в базу вставиться данные, но при этом произойти сетевая ошибка, и ты повторно проведешь вставку данных

Я не встречал на своем опыте кейса, когда нужно было что-то ретраить в бд, т.к. обычно база располагается в той же инфраструктуре, что и основное приложение.
А если такой кейс раз в пять лет когда то и возникает, то пользователь просто получит 500, обновит страницу, и даже если что-то создалось, то благодаря перезагрузке он увидит всегда консистентное состояние

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/database.go
> +func ConnectDB(config Config, logger *zap.SugaredLogger) *DBPool {
По факту это конструктор для структуры, по канонам го тебе нужно его назвать NewDBPool, чтобы не путать других твоих коллег в будущих проектах

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/handlers.go
> +	}
Не совсем понимаю, зачем тебе везде это обрабатывать
По факту то, что ты можешь создать несуществующий dbpool - это уже неправильное состояние твоего приложения
Отдавай ошибку и потом паникуй в момент старта твоего сервера, а не 500 тут

2024-05-11 15:31 UTC, gonozov0 commented on internal/server/handlers.go
> +	}
Подожди, ты получается и в MemStorage записываешь и в db?
Запишись на 1:1, тебе нужно научиться через механизм DI (dependency injection) гибко подкладывать нужный Storage при старте твоего приложения и тут использовать уже интерфейс для этих дел

2024-05-14 07:13 UTC, gonozov0 commented on internal/server/handlers.go
> +func NewHandler(storage *MemStorage, config Config, logger *zap.SugaredLogger, dbpool MetricsModel) *Handler {
Передавать интерфейс, [пример](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handler.go#L18)

2024-05-14 07:15 UTC, gonozov0 commented on internal/server/server.go
> +	srv := NewHandler(storage, config, logger, dbpool)
А здесь происходит передача нужно конкретной реализации стораджа, [пример](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/server.go#L43)

2024-05-14 07:24 UTC, gonozov0 commented on internal/agent/agent.go
>  			return fmt.Errorf("not supported type: %v", value.Kind())
Как пример (всегда кастуем к нужному типу, когда берем из memStats)
https://github.com/gonozov0/go-musthave-devops/blob/main/internal/agent/metrics.go#L31-L60

2024-05-15 21:07 UTC, pisarevaa commented
@gonozov0 спасибо за встречу 1:1, учел комментарии, серьезно переработал проект

2024-05-16 07:13 UTC, gonozov0 approved these changes
Отличная работа, все критичные моменты были поправлены 💪

2024-05-16 07:13 UTC, gonozov0 commented on internal/server/handlers.go
> +func (s *Handler) StoreMetricsJSON(w http.ResponseWriter, r *http.Request) { //nolint:funlen /// TODO: refactor
👍

2024-05-16 07:13 UTC, gonozov0 commented on internal/server/handlers.go
>  	}
Чтобы уменьшить объем этой функции, можно вынести эту логику полностью в метод StoreMetric у MemStorage, потому что для DBStorage сохранять что-то в файл нет смысла, только лишнии операции

2024-05-16 07:13 UTC, gonozov0 commented on internal/server/handlers.go
> +	if err != nil {
Это можно перенести в метод ToJSON у metric

2024-05-16 07:14 UTC, gonozov0 commented on internal/server/disk.go
> +func SaveToDosk(metrics []storage.Metrics, filename string) error {
SaveToDisk

2024-05-16 10:19 UTC, merged