Iter5
pisarevaa/metrics pull request #5
Opened 2024-04-03 11:48 UTC by pisarevaa

2024-04-04 09:33 UTC, gonozov0 requested changes
Отличная работа 👍
Хорошо продумал общую структуру и распараллеливание сбора и отправки логов по таймеру

Если есть желание, рекомендую сразу подключить к проекту [golangci-lint](https://golangci-lint.run/) и [golden config](https://gist.github.com/maratori/47a4d00457a92aa426dbd48a18776322) для него
Для удобства лучше также [установить](https://github.com/gonozov0/go-echo-ddd-template/tree/main?tab=readme-ov-file#pre-commit-hooks) и [настроить](https://github.com/gonozov0/go-echo-ddd-template/blob/main/.pre-commit-config.yaml#L22) precommit хуки, чтобы линтер отрабатывал перед каждым коммитом
Дополнительно можно и в [ci добавить](https://github.com/gonozov0/go-echo-ddd-template/blob/main/.github/workflows/lint%26test.yml#L51)

2024-04-04 09:33 UTC, gonozov0 commented on cmd/agent/main.go
> +	storage := agent.MemStorage{}
Правильнее в go делать всегда конструкторы для сложных структур с префиксом New, который возвращают сам объект. Если в будущем появится какая-то логика инициализации, не придется везде менять вызов
[как пример](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/infrastructure/users/in_memory.go#L21)

2024-04-04 09:33 UTC, gonozov0 commented on internal/agent/config.go
> +func GetConfigs() Config {
Логичнее GetConfig

2024-04-04 09:33 UTC, gonozov0 commented on cmd/agent/main.go
> +	service := agent.Service{Storage: &storage, Client: client, Config: config}
аналогично

2024-04-04 09:33 UTC, gonozov0 commented on cmd/agent/main.go
> +	storage.Init()
Инициализация как раз должна быть уже в NewStorage

2024-04-04 09:33 UTC, gonozov0 commented on cmd/agent/main.go
> +	wg.Wait()
👍

2024-04-04 09:33 UTC, gonozov0 commented on cmd/server/main.go
> +}
Это стоит вынести в internal/server/

2024-04-04 09:33 UTC, gonozov0 commented on internal/server/server.go
> +type Server struct {
Я бы эту структуру и файл называл Handler, а не Server, т.к. по факту ты тут описываешь именно обработчики

2024-04-04 09:33 UTC, gonozov0 commented on cmd/server/main_test.go
Тесты рядом с main не стоит класть, т.к. это не отражает суть тестов внутри и в будущем с дополнительными тестами этот файл тогда разрастется до нечитаемого количества строк

т.к. это тесты на хендлеры, то я бы предложил тебе перенести его в internal/server/handlers/handlers_test/savelogs_test.go

2024-04-04 09:33 UTC, gonozov0 commented on cmd/server/main_test.go
> +	defer ts.Close()
Т.к. в будущем появятся тесты на другие хендлеры можно сейчас или просто иметь ввиду потом, что можно вынести эту общую для всех логику в инициализацию Suite
[как пример ](https://github.com/gonozov0/go-echo-ddd-template/blob/main/internal/application/users/handlers/handlers_test/suite_test.go#L20)

2024-04-04 09:33 UTC, gonozov0 commented on internal/agent/agent.go
> +			panic("not supported type")
паниковать можно только в main, в твоем случае, т.к. еще не знаком, как обрабатывать ошибки в горутинах, то логировать на самом верхнем уровне горутины и паниковать
А тут нужно возвращать ошибку из метода

2024-04-04 09:33 UTC, gonozov0 commented on internal/agent/agent_test.go
> +	assert.True(t, len(service.Storage.Gauge) == 28)
Лучше использовать assert.Equal, будет лучше вывод, что ожидали, а что не так получили

2024-04-04 09:33 UTC, gonozov0 commented on internal/storage/storage.go
> +	Counter map[string]int64
Лучше сделать приватными, любое получения и добавление реализуем через публичные методы

2024-04-04 09:33 UTC, gonozov0 commented on internal/agent/storage.go
> +	Counter map[string]int64
Тут тоже лучше сделать приватными + написать публичные метод на сохранение и получение с очисткой

2024-04-06 15:13 UTC, pisarevaa commented
@gonozov0 спасибо большое за ревью, много всего переработал

2024-04-06 15:15 UTC, pisarevaa commented on cmd/server/main_test.go
Вынес в internal тесты, в след. релизах сделаю папку с тестами, пока в один файл запихнул

2024-04-07 11:19 UTC, gonozov0 approved these changes
Отлично все поправил 💪
Критичных моментов больше не осталось, заранее поставлю апрув

2024-04-07 11:19 UTC, gonozov0 commented on .github/workflows/lint&test.yml
> +          - 6379:6379
Эти строки лучше удалить, т.к. преподнятый редис для твоих тестов тебе не нужен, только лишнюю личную квоту гитхаба тратит

2024-04-07 11:19 UTC, gonozov0 commented on .github/workflows/lint&test.yml
> +        path: coverage.out
Аналогично, тесты твои и так запускаются через workflow из шаблона проекта, а сохранение test coverage-а тебе также не нужено

2024-04-07 11:19 UTC, gonozov0 commented on internal/storage/storage.go
Т.к. это используется только server-ом, то лушче положить в internal/server/

2024-04-07 19:15 UTC, merged